# Generated by Django 3.2.4 on 2021-07-02 14:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_comentario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comment',
            field=ckeditor.fields.RichTextField(verbose_name='Comentario'),
        ),
    ]
