# Generated by Django 3.2.4 on 2021-07-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_alter_comentario_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Clave')),
                ('usuario', models.TextField(verbose_name='Usuario')),
                ('mensaje', models.TextField(verbose_name='Comentario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
            ],
            options={
                'verbose_name': 'Comentario Contacto',
                'verbose_name_plural': 'Comentarios Contacttos',
                'ordering': ['-created'],
            },
        ),
    ]
